name: Analyse Project
on: [push, pull_request]

jobs:
  scan_project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout repo to remote machine

      - name: Set up OpenJDK13 
        uses: actions/setup-java@v1
        with:
          java-version: '13'

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      # Will post to the remote site @ sonarcloud.io  
      - name: Build and analyze
        run: |
          cd $GRADLE_DIR
          chmod +x ./gradlew
          ./gradlew build sonarqube --info 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          GRADLE_DIR: 'source' # Modify this to wherever './gradlew' is 
          